trigger:
- master

pool:
  vmImage: ubuntu-latest

steps:
- task: Gradle@2
  inputs:
    gradleWrapperFile: 'gradlew'
    gradleOptions: '-Xmx3072m'
    javaHomeOption: 'JDKVersion'
    jdkVersionOption: '1.8'
    jdkArchitectureOption: 'x64'
    publishJUnitResults: false
    testResultsFiles: '**/TEST-*.xml'
    tasks: 'clean build'

- task: Docker@2
  inputs:
    containerRegistry: 'spotifymscontainerregistry'
    repository: 'spotify-user'
    command: 'buildAndPush'
    tags: 'latest'
    Dockerfile: '**/Dockerfile'
